### PR TITLE
Handle %:z %::z %:::z time formats

### LINKED ISSUE #7: datetime.strftime issues
PyYAML parses date-time strings into a `datetime.datetime` instance and dumps it out in a format that has a space between the date and the time. We should either:
* Modify the parser to parse date-time strings into str so it can remain unchanged.
* Modify the dumper to dump date-time strings using the specified default format `--time-format=FORMAT`.

The other problem is that `datetime.strftime` does not support `%:z`, `%::z`, etc. (See `man  date` for meaning of these format codes.)

### PR DESCRIPTION
**Pull request by matthewrmshin**
Handle `%:z %::z %:::z` format codes for time variable substitutions and default time stamp formatting. (See `man date` on a GNU system for an explanation of these format codes.)

Always use Z for UTC/+00:00 time zone.

Change default format to  `%FT%T%:z`. (It was `%FT%T%z` which had an inconsistency between the displays of the time and the time zone.)

Ensure time stamp values (values that are parsed into `datetime.datetime` object by PyYAML) are dumped in the default time format `%FT%T%:z`.

Close #7.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Hopefully, this fixes what's reported by @yaswant.

**Comment by steoxley** [comment]
I've had a preliminary look through. Seems quite thorough! Can you update the README.md to include examples of this functionality which will help with finalising the review.

**Review by yaswant — APPROVED** [review]

**Review by KrissyRayD242 — APPROVED** [review]
Looks good!

**Review by steoxley — APPROVED** [review]
I've looked through all of the files and although I haven't personally tested, I am happy with the changes.

**Pull request merged**
