### PR TITLE
Add Sphinx doc

### PR DESCRIPTION
**Pull request by matthewrmshin**
Improve docstrings to satisfy Sphinx build. Move user doc from README.md to Sphinx doc.

### CODE REVIEW

**Review by steoxley — CHANGES_REQUESTED** [review]
Really like this! Only a few suggestions:
- Update the Copyright
- Consider running Sphinx with, -W --keep-going, so that warnings don't creep in.

**Comment by matthewrmshin** [comment]
Comments addressed.

**Review by steoxley — APPROVED** [review]
Suggested changes made. Approved!

**Review by KrissyRayD242 — APPROVED** [review]
I read all the docs. 
I followed the command line documentation, but did not experiment with the Python API.

**Pull request merged**
